### ISSUE TITLE
recursive name sanitization of records of type RECORD fails

### ISSUE THREAD

**Issue by riccardomc** [bxparks/bigquery-schema-generator#43]
Names in `RECORD` fields are not sanitized. I reproduced the issue consistently by introducing the following test data:

```
# Sanitize the names to comply with BigQuery, recursively.
DATA sanitize_names
{ "r" : { "a-name": [1, 2] } }
SCHEMA
[
  {
    "fields": [
      {
        "mode": "REPEATED",
        "name": "a_name",
        "type": "INTEGER"
      }
    ],
    "mode": "NULLABLE",
    "name": "r",
    "type": "RECORD"
  }
]
END
```

Which results in the following failure:
```
======================================================================
FAIL: test (__main__.TestFromDataFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_generate_schema.py", line 423, in test
    self.verify_data_chunk(chunk_count, chunk)
  File "./tests/test_generate_schema.py", line 450, in verify_data_chunk
    self.assertEqual(expected, schema)
AssertionError: Lists differ: [Orde[62 chars]', 'a_name'), ('type', 'INTEGER')])]), ('mode'[46 chars]')])] != [Orde[62 chars]', 'a-name'), ('type', 'INTEGER')])]), ('mode'[46 chars]')])]

First differing element 0:
Order[61 chars]', 'a_name'), ('type', 'INTEGER')])]), ('mode'[45 chars]D')])
Order[61 chars]', 'a-name'), ('type', 'INTEGER')])]), ('mode'[45 chars]D')])

  [OrderedDict([('fields',
                 [OrderedDict([('mode', 'REPEATED'),
-                              ('name', 'a_name'),
?                                         ^

+                              ('name', 'a-name'),
?                                         ^

                               ('type', 'INTEGER')])]),
                ('mode', 'NULLABLE'),
                ('name', 'r'),
                ('type', 'RECORD')])]

----------------------------------------------------------------------
Ran 14 tests in 0.006s
```

**Comment by bxparks** [comment]
Released v1.0 with this fix. Thanks for the PR.
