### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by lekesh** [bxparks/bigquery-schema-generator#86]
I used _bigquery-schema-generator_ for relatively small CSV file (320 mb). After reading 30,000 lines Attribute error was thrown stating:
AttributeError: 'NoneType' object has no attribute 'lower'
```
INFO:root:Processing line 1000
INFO:root:Processing line 2000
INFO:root:Processing line 3000
INFO:root:Processing line 4000
INFO:root:Processing line 5000
INFO:root:Processing line 6000
INFO:root:Processing line 7000
INFO:root:Processing line 8000
INFO:root:Processing line 9000
INFO:root:Processing line 10000
INFO:root:Processing line 11000
INFO:root:Processing line 12000
INFO:root:Processing line 13000
INFO:root:Processing line 14000
INFO:root:Processing line 15000
INFO:root:Processing line 16000
INFO:root:Processing line 17000
INFO:root:Processing line 18000
INFO:root:Processing line 19000
INFO:root:Processing line 20000
INFO:root:Processing line 21000
INFO:root:Processing line 22000
INFO:root:Processing line 23000
INFO:root:Processing line 24000
INFO:root:Processing line 25000
INFO:root:Processing line 26000
INFO:root:Processing line 27000
INFO:root:Processing line 28000
INFO:root:Processing line 29000
INFO:root:Processing line 30000
INFO:root:Processed 30334 lines
Traceback (most recent call last):
  File "/usr/local/bin/generate-schema", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/bigquery_schema_generator/generate_schema.py", line 1074, in main
    generator.run(schema_map=existing_schema_map)
  File "/usr/local/lib/python3.7/dist-packages/bigquery_schema_generator/generate_schema.py", line 707, in run
    input_file, schema_map=schema_map
  File "/usr/local/lib/python3.7/dist-packages/bigquery_schema_generator/generate_schema.py", line 201, in deduce_schema
    schema_map=schema_map,
  File "/usr/local/lib/python3.7/dist-packages/bigquery_schema_generator/generate_schema.py", line 237, in deduce_schema_for_record
    canonical_key = self.sanitize_name(key).lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by abroglesc** [comment]
You are going to need to provide the data of the line that you are trying to generate a schema from. This more than likely means that you have invalid json on whatever line this error'd in.

**Comment by lekesh** [comment]
> You are going to need to provide the data of the line that you are trying to generate a schema from. This more than likely means that you have invalid json on whatever line this error'd in.

Everything looks normal in 30335th line. The data I am working on is quite sensitive so I can't share the data.
If there are any workarounds for this, kindly suggest.

**Comment by bxparks** [comment]
Without a reproducible example, there's little that we can do.
Did you try narrowing down the offending line at or near 30334? Once you find the problem, maybe you can anonymize the data so that it reproduces the problem. Then you can upload the sample into this ticket.

**Comment by bxparks** [comment]
Closing.
